title: Laravel Backup Utils
description: A modern backup solution for Laravel applications
baseurl: "/spatie-laravel-backup-utils"
url: "https://ubxty.github.io"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
author:
  name: Ravdeep Singh
  twitter:
    username: ubxty
    card: summary_large_image
  github:
    username: ubxty
  linkedin:
    username: ravdeep-singh-ubxty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .github
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - composer.json
  - composer.lock
  - phpunit.xml
  - tests
  - src
  - config

# Include specific files
include:
  - _layouts
  - _includes
  - assets
  - docs/v1
  - docs/index.md

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: Ravdeep Singh
      twitter:
        username: ubxty
        card: summary_large_image
  - scope:
      path: "docs/v1"
    values:
      layout: "default"
      permalink: /docs/v1/:title/
      author: Ravdeep Singh
      twitter:
        username: ubxty
        card: summary_large_image

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Navigation
nav_items:
  - title: Introduction
    url: /docs/v1/introduction
  - title: Installation
    url: /docs/v1/installation
  - title: Configuration
    url: /docs/v1/configuration
  - title: Usage
    url: /docs/v1/usage

# Build settings
destination: _site
keep_files:
  - assets
  - .nojekyll 