title: Laravel Backup Utils
description: A modern backup solution for Laravel applications
baseurl: "/spatie-laravel-backup-utils"
url: "https://ubxty.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
author:
  name: Ravdeep Singh
  twitter:
    username: ubxty
    card: summary_large_image
  github:
    username: ubxty
  linkedin:
    username: ravdeep-singh-ubxty

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'

# Sass/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .github
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - composer.json
  - composer.lock
  - phpunit.xml
  - tests
  - src
  - config

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: Ravdeep Singh
      twitter:
        username: ubxty
        card: summary_large_image
  - scope:
      path: "v1"
      type: "pages"
    values:
      layout: "default"
      version: "v1"
      author: Ravdeep Singh

# Navigation structure
navigation:
  v1:
    - title: Introduction
      url: /v1/introduction/
      order: 1
    - title: Installation
      url: /v1/installation/
      order: 2
    - title: Configuration
      url: /v1/configuration/
      order: 3
    - title: Usage
      url: /v1/usage/
      order: 4

# Build settings
destination: _site
keep_files:
  - assets
  - .nojekyll 